### ISSUE TITLE
Hardcoded SQL variables

### ISSUE THREAD

**Issue by pmakin** [teeworlds-instagib-elo/iCTFX#8]
Code contains few hardcoded sql variables (db, user, pass, host, port)
This can create issues with setting up server in future or if someone will want to host it

References:
https://github.com/teeworlds-instagib-elo/iCTFX/blob/e3233673f2cca5d64fa6c8ff1602ca95eb1f7ead/src/game/server/sql_handler.cpp#L18
https://github.com/teeworlds-instagib-elo/iCTFX/blob/e3233673f2cca5d64fa6c8ff1602ca95eb1f7ead/src/game/server/sql_handler.cpp#L62
https://github.com/teeworlds-instagib-elo/iCTFX/blob/e3233673f2cca5d64fa6c8ff1602ca95eb1f7ead/src/game/server/sql_handler.cpp#L80
https://github.com/teeworlds-instagib-elo/iCTFX/blob/065676bda134399b174150273b6bad79a98ed329/src/game/server/gamemodes/DDRace.cpp#L34

**Comment by hardliner66** [comment]
Very good idea. Even if it's just to remove the duplicate strings. Anyway a good idea to future proof.

**Comment by hardliner66** [comment]
fixed in #13
